import test from 'node:test';
import assert from 'node:assert/strict';
import {newPersonalNames,nameRow,parsePersonalNames,personalSummary,previewName} from '../lib/personal-names.ts';
import {newLetteringItem,letteringLayout,letteringSummary} from '../lib/lettering.ts';
import {newQuote,parseQuote,reorder,validate,manualThreads} from '../lib/quote.ts';
function sample(){const q=newQuote(),personal=newPersonalNames('山口');personal.rows[0].first='太郎';personal.rows.push({...nameRow(),last:'ふかみ',size:'L',quantity:2});q.products[0].spots[0].lettering={enabled:true,pocketAngle:0,items:[{...newLetteringItem('会社名'),text:'山口建設'},{...newLetteringItem('個人名'),text:'山口 太郎',personal}]};return q;}
test('roster survives parse, reorder and independent copies',()=>{const q=sample();assert.deepEqual(parseQuote(q),q);const r=reorder(q,'same');assert.deepEqual(r.products[0].spots[0].lettering,q.products[0].spots[0].lettering);r.products[0].spots[0].lettering.items[1].personal.rows[0].last='変更';assert.equal(q.products[0].spots[0].lettering.items[1].personal.rows[0].last,'山口');assert.match(letteringSummary(q.products[0].spots[0].lettering),/合計数量：3着/)});
test('same-place positions and alignment match company bounding box',()=>{const v=sample().products[0].spots[0].lettering,p=v.items[1].personal;p.position='上';p.align='左寄せ';const l=letteringLayout(60,40,v),c=l.items[0],n=l.items[1];assert.ok(Math.abs((n.x-n.bw/2)-(c.x-c.bw/2))<1e-8);assert.ok(n.y+n.bh/2<c.y-c.bh/2);p.place='異なる場所';assert.equal(letteringLayout(60,40,v).items.length,1)});
test('preview selection, no-name and totals',()=>{const p=newPersonalNames('山田');p.rows.push({...nameRow(),first:'太郎',quantity:4});p.previewId=p.rows[1].id;assert.equal(previewName(p),'太郎');p.noName=true;assert.equal(previewName(p),'');assert.match(personalSummary(p),/合計数量：5着/);assert.match(personalSummary(p),/会社名のみ/)});
test('validate blank names and unsupported common font; drafts remain recoverable',()=>{const q=sample(),t=q.products[0].spots[0].lettering.items[1];t.font='行書体';assert.ok(validate(q).some(e=>e.message.includes('共通して')));t.personal.rows[0].last='';t.personal.rows[0].first='';assert.ok(validate(q).some(e=>e.message.includes('各行')));t.personal.noName=true;assert.ok(!validate(q).some(e=>e.message.includes('各行')))});
test('limits and legacy conversion',()=>{const p=newPersonalNames();assert.throws(()=>parsePersonalNames({...p,rows:[]}));assert.throws(()=>parsePersonalNames({...p,rows:[{...p.rows[0],quantity:51}]}));assert.throws(()=>parsePersonalNames({...p,rows:[p.rows[0],p.rows[0]]}));const q=sample();delete q.products[0].spots[0].lettering.items[1].personal;assert.equal(manualThreads(q).products[0].spots[0].lettering.items[1].personal.rows[0].last,'山口 太郎')});
test('center basis includes logo only when selected and preserves legacy default',()=>{const q=sample(),v=q.products[0].spots[0].lettering;v.items[0].position='右';const p=v.items[1].personal;p.position='下';p.align='中央寄せ';let l=letteringLayout(60,40,v);assert.equal(l.items[1].x,l.items[0].x);p.centerBasis='ロゴ＋会社名全体の中央';l=letteringLayout(60,40,v);const c=l.items[0];assert.equal(l.items[1].x,(-30+c.x+c.bw/2)/2);assert.notEqual(l.items[1].x,c.x);assert.equal(parseQuote(q).products[0].spots[0].lettering.items[1].personal.centerBasis,p.centerBasis);assert.equal(reorder(q,'same').products[0].spots[0].lettering.items[1].personal.centerBasis,p.centerBasis);assert.match(personalSummary(p),/ロゴ＋会社名全体の中央/);assert.throws(()=>parsePersonalNames({...p,centerBasis:'invalid'}));});
