import test from 'node:test';
import assert from 'node:assert/strict';
import {detectPalette,nearestThread,threadColors,threadText} from '../lib/thread-colors.ts';
import {newQuote,parseQuote,reorder,resizeSpot,locations} from '../lib/quote.ts';
test('all 29 registered thread numbers are unique and exact screen colors match themselves',()=>{assert.equal(threadColors.length,29);assert.equal(new Set(threadColors.map(c=>c.number)).size,29);for(const c of threadColors)assert.equal(nearestThread(c.hex).number,c.number);assert.equal(nearestThread('#ffffff').number,'1198');assert.equal(nearestThread('#000000').number,'1197')});
test('transparent pixels do not add colors; opaque white stays selectable',()=>{const pixels=new Uint8ClampedArray([255,0,0,0,255,255,255,255,255,255,255,255,17,18,22,255,17,18,22,255]);const colors=detectPalette(pixels);assert.equal(colors.length,2);assert(colors.includes('#ffffff'));assert(colors.includes('#111216'));assert.deepEqual(detectPalette(new Uint8ClampedArray([255,0,0,0])),[])});
test('palette collapses small compression differences and retains two flat colors',()=>{const colors=detectPalette(new Uint8ClampedArray([141,37,37,255,143,37,37,255,143,39,37,255,244,243,237,255,245,243,237,255]));assert.equal(colors.length,2)});
test('new placement, dimensions, body and thread choices survive parse and reorder',()=>{const q=newQuote(),p=q.products[0],s=p.spots[0];p.previewColor='#112244';s.location='背面えり下';s.axis='height';s.threadMode='指定する';s.threadSelections=[{source:'#ffffff',number:'1198'},{source:'#f4f3ed',number:'1198'}];s.thread=threadText(s.threadSelections);assert.equal(s.thread,'白（糸番号 1198）');assert.deepEqual(parseQuote(q),q);assert.deepEqual(reorder(q,'same').products[0].spots[0].threadSelections,s.threadSelections);for(const location of locations){s.location=location;assert.equal(parseQuote(q).products[0].spots[0].location,location)}s.threadSelections[0].number='fake';assert.throws(()=>parseQuote(q))});
test('height constraint preserves logo aspect ratio',()=>{const s=newQuote().products[0].spots[0];s.asset={id:'test',name:'x.png',type:'image/png',width:200,height:100};assert.deepEqual([resizeSpot(s,'height','41').width,resizeSpot(s,'height','41').height],['82','41'])});
