'use client';
import {useId} from 'react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {assetUrl} from '@/lib/client';
import type {Spot} from '@/lib/quote';
export function Field({label,value,onChange,id,required=false,type='text',placeholder='',min,step}: {label:string;value:string;onChange:(v:string)=>void;id?:string;required?:boolean;type?:string;placeholder?:string;min?:string;step?:string}){const generated=useId();const key=id||generated;return <label className="field" htmlFor={key}>{label}{required&&<em>必須</em>}<input id={key} value={value} onChange={e=>onChange(e.target.value)} type={type} placeholder={placeholder} min={min} step={step} maxLength={type==='number'?undefined:500} aria-required={required}/></label>}
export function Choice({label,value,onChange,options,id,disabled=[]}:{label:string;value:string;onChange:(v:string)=>void;options:string[];id?:string;disabled?:string[]}){const key=useId();return <div className="field"><label id={`${id||key}-label`} htmlFor={id||key}>{label}</label><Select value={value} onValueChange={v=>onChange(v||'')}><SelectTrigger id={id||key} aria-labelledby={`${id||key}-label`}><SelectValue>{value||'選択してください'}</SelectValue></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v} disabled={disabled.includes(v)}>{v}</SelectItem>)}</SelectContent></Select></div>}
export function Check({label,checked,onChange,id}:{label:string;checked:boolean;onChange:(v:boolean)=>void;id?:string}){const key=useId();return <label className="checkrow" htmlFor={id||key}><Checkbox id={id||key} checked={checked} onCheckedChange={v=>onChange(!!v)}/><span>{label}</span></label>}
export function Notes({label,value,onChange,id}:{label:string;value:string;onChange:(v:string)=>void;id?:string}){const key=useId();return <label className="field" htmlFor={id||key}>{label}<textarea id={id||key} value={value} onChange={e=>onChange(e.target.value)} maxLength={5000}/></label>}
export function LogoPreview({spot}:{spot:Spot}){if(!spot.asset)return null;return <><div className="dimension-preview"><img src={assetUrl(spot.asset)} alt={`ロゴ原稿：${spot.asset.name}`} style={{width:'240px',aspectRatio:Number(spot.width)>0&&Number(spot.height)>0?`${spot.width} / ${spot.height}`:undefined,objectFit:'fill'}}/><div className="width">横 {spot.width||'未指定'} mm</div><div className="height">縦 {spot.height||'未指定'} mm</div></div><p className="muted" style={{marginTop:8}}>配置・寸法の参考図です。実際の糸色や縫い目を再現するものではありません。</p></>}

