import {productColorText,bodyColor} from './body-color.ts';
import {PDFDocument,rgb,type PDFPage,type PDFFont} from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import {displayAsset,threadInstruction,deliveryText,subtotal,total,type Quote,type Asset} from './quote.ts';
export async function createQuotePdf(q:Quote,fontBytes:Uint8Array,loadImage:(a:Asset)=>Promise<Uint8Array>){
 const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const font=await pdf.embedFont(fontBytes,{subset:false});pdf.setTitle('ロゴ刺繍 見積依頼書');pdf.setSubject(q.id);pdf.setLanguage('ja-JP');let page!:PDFPage,y=0;const margin=42,width=511;
 const newPage=()=>{page=pdf.addPage([595.28,841.89]);y=775;page.drawLine({start:{x:42,y:811},end:{x:553,y:811},thickness:3,color:rgb(.08,.3,.46)})};
 const ensure=(h:number)=>{if(y-h<48)newPage()};
 function lines(value:string,size:number){const result:string[]=[];for(const paragraph of value.replace(/\r/g,'').split('\n')){let row='';for(const char of paragraph){if(font.widthOfTextAtSize(row+char,size)>width&&row){result.push(row);row=''}row+=char}result.push(row)}return result}
 function text(value:string,size=10.5){for(const line of lines(value,size)){ensure(size*1.7);page.drawText(line,{x:margin,y,font,size,color:rgb(.1,.17,.24)});y-=size*1.7}y-=4}
 function heading(value:string){ensure(40);y-=8;text(value,15);y-=6}
 newPage();text('ロゴ刺繍 見積依頼書',22);text(`依頼番号：${q.id}`);text(`作成日：${new Date(q.updatedAt).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo'})}`);text('この書類は見積もりの依頼内容です。発注・メール送信はしていません。');heading('お客様情報');text(`会社組織名：${q.customer.company||'—'}\nご担当者様名：${q.customer.name}\n電話番号：${q.customer.phone||'—'}\nLINE登録：${q.customer.lineRegistration||'未選択'}`);heading('必要納期');text(deliveryText(q));if(q.deliveryNotes)text(`納期の補足：${q.deliveryNotes}`);heading('商品一覧');q.products.forEach((p,i)=>text(`${i+1}. ${p.name||'商品未指定'} ／ ${p.kind} ／ ${productColorText(p)||'未指定'} ／ ${subtotal(p)>0?subtotal(p)+'着':'数量未指定'}`));text(`合計：${q.products.length}商品・${total(q)>0?total(q)+'着':'数量未指定'}`);if(q.sourceId)text(`再注文の元依頼：${q.sourceId}`);text(`顧客ID：${q.customerId}\n加工区分：ロゴ刺繍`);
 for(let i=0;i<q.products.length;i++){const p=q.products[i];newPage();heading(`商品 ${i+1}　${p.name||'商品未指定'}`);text(`種類：${p.kind}\n品番：${p.sku||'—'}\n管理番号：${p.manageNo||'—'}\n色：${productColorText(p)||'未指定'}\n素材・混率：${p.material||'未指定'}`);text('サイズ・数量：'+(p.sizes.filter(s=>s.size&&s.quantity).map(s=>`${s.size} × ${s.quantity}着`).join(' ／ ')||'未指定'));text(`小計：${subtotal(p)>0?subtotal(p)+'着':'数量未指定'}`);
 for(let j=0;j<p.spots.length;j++){const s=p.spots[j];heading(`刺繍箇所 ${j+1} ／ ${s.location==='その他'?s.other:s.location}`);text(`希望寸法：横 ${s.width} × 縦 ${s.height} mm\n糸色・糸番号：${threadInstruction}\n刺繍型データ：${s.pattern}${s.pattern==='あり'?'\n型データの参照：'+s.reference:''}`);if(s.notes)text(`補足：${s.notes}`);if(s.asset){text(`原稿ファイル：${s.asset.name}`);const shown=displayAsset(s.asset);const bytes=await loadImage(shown);const image=shown.type==='image/jpeg'?await pdf.embedJpg(bytes):await pdf.embedPng(bytes);const ratio=Number(s.width)/Number(s.height);const drawW=Math.min(300,160*ratio),drawH=drawW/ratio;ensure(drawH+70);const x=margin+25;y-=drawH;page.drawRectangle({x:x-10,y:y-10,width:drawW+20,height:drawH+20,color:rgb(...([1,3,5].map(i=>parseInt((p.previewColor||bodyColor(p.color)).slice(i,i+2),16)/255) as [number,number,number])),borderColor:rgb(.75,.8,.85),borderWidth:.7});page.drawImage(image,{x,y,width:drawW,height:drawH});page.drawLine({start:{x,y:y-22},end:{x:x+drawW,y:y-22},thickness:.6});page.drawText(`横 ${s.width} mm  /  縦 ${s.height} mm`,{x,y:y-38,font,size:10});y-=56;text('寸法の参考図です。実際の糸色や縫い目を再現するものではありません。',9)}}
 }
 heading('業者への確認事項');text('加工可否・型代・加工単価・針数等は業者確認となります。画像から針数や価格を確定していません。型データや依頼履歴がある場合も、型代不要・同条件での加工可能を確約するものではありません。');const pages=pdf.getPages();pages.forEach((p,i)=>p.drawText(`${i+1} / ${pages.length}`,{x:510,y:25,font,size:9,color:rgb(.4,.45,.5)}));return pdf.save();
}
export async function browserPdf(q:Quote){const font=await fetch('/fonts/NotoSansJP-Regular.ttf');if(!font.ok)throw new Error('日本語フォントを読み込めません。再試行してください');return createQuotePdf(q,new Uint8Array(await font.arrayBuffer()),async a=>{const response=await fetch(`/api/files?id=${encodeURIComponent(a.id)}`);if(!response.ok)throw new Error(`ロゴ原稿を読み込めません：${a.name}`);const blob=await response.blob();if(a.type!=='image/webp')return new Uint8Array(await blob.arrayBuffer());const url=URL.createObjectURL(blob);try{const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('画像の変換に失敗しました'));img.src=url});const canvas=document.createElement('canvas');const scale=Math.min(1,1600/Math.max(image.width,image.height));canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);const png=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('画像の変換に失敗しました')),'image/png'));return new Uint8Array(await png.arrayBuffer())}finally{URL.revokeObjectURL(url)}})}



