import {newPersonalNames,personalText,rowName} from './personal-names.ts';
import {allowedLetteringFonts,canonicalFont} from './lettering-fonts.ts';
import {parseLettering,type Lettering} from './lettering.ts';
import {manualThreadText,threadColors} from './thread-colors.ts';
export type Asset={id:string;name:string;type:string;width:number;height:number;preview?:{id:string;width:number;height:number}};
export type Spot={lettering?:Lettering;id:string;location:string;other:string;width:string;height:string;lock:boolean;axis?:'width'|'height';threadSelections?:{source:string;number:string;confirmed?:boolean;colorName?:string}[];threadMode:string;thread:string;pattern:string;reference:string;notes:string;asset:Asset|null};
export type Product={id:string;name:string;kind:string;sku:string;manageNo:string;color:string;colorNotes?:string;previewColor?:string;material:string;sizes:{id:string;size:string;quantity:string}[];spots:Spot[]};
export type Quote={version:1;id:string;customerId:string;process:'logo-embroidery';sourceId:string|null;customer:{name:string;company:string;email?:string;phone:string;lineRegistration?:string};products:Product[];delivery:string;deliveryNotes:string;checked:boolean;step:number;updatedAt:string};
export type Issue={step:number;target:string;message:string};
export const threadInstruction='ロゴの元データをもとに、刺繍屋さんが糸色・糸番号を選定します。';
export const steps=['お客様情報','商品情報','刺繍情報','必要納期','確認事項'];
export const sizes=['SS','S','M','L','LL','3L','4L','5L','6L','フリー'];
export const locations=['左胸ポケット上','左胸縫い目上','右胸ポケット上','右胸縫い目上','左肩','右肩','背面えり下','背面','その他'];
export const uid=()=>crypto.randomUUID();
export const newSize=()=>({id:uid(),size:'',quantity:''});
export const newSpot=():Spot=>({id:uid(),location:'左胸ポケット上',other:'',width:'',height:'',lock:true,threadMode:'未選択',thread:'',pattern:'不明',reference:'',notes:'',asset:null});
export const newProduct=():Product=>({id:uid(),name:'',kind:'未指定',sku:'',manageNo:'',color:'',material:'',sizes:[newSize()],spots:[newSpot()]});
export const newQuote=():Quote=>({version:1,id:uid(),customerId:uid(),process:'logo-embroidery',sourceId:null,customer:{company:'',name:'',phone:''},products:[newProduct()],delivery:'',deliveryNotes:'',checked:false,step:1,updatedAt:new Date().toISOString()});
export function copyProduct(p:Product,withSpots:boolean):Product{return {...structuredClone(p),id:uid(),sizes:[newSize()],spots:withSpots?p.spots.map(s=>({...structuredClone(s),id:uid()})):[newSpot()]};}
export function subtotal(p:Product){return p.sizes.reduce((n,s)=>n+(s.size.trim()&&/^\d+$/.test(s.quantity)&&Number(s.quantity)>0?Number(s.quantity):0),0)}
export function total(q:Quote){return q.products.reduce((n,p)=>n+subtotal(p),0)}
export function duplicates(p:Product){const seen=new Set<string>();return p.sizes.filter(s=>{const k=s.size.trim().toUpperCase();if(!k)return false;if(seen.has(k))return true;seen.add(k);return false}).map(s=>s.size)}
export function validDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const d=new Date(value+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===value;}
export function fiveDaysBefore(value:string){if(!value)return '';if(!validDate(value))throw new Error('日付を確認してください');const d=new Date(value+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-5);return d.toISOString().slice(0,10)}
export const deliveryNotice='通常、ご注文から1週間〜10日ほどでお届けします。繁忙期は2週間程度かかる場合がございます。\n納期のご指定は承っておりません。あらかじめご了承ください。';
export function deliveryText(_q:Quote){return deliveryNotice;}
export function reorder(q:Quote,mode:'same'|'product'|'embroidery'):Quote{return {...structuredClone(q),id:uid(),sourceId:q.id,products:q.products.map(p=>({...structuredClone(p),id:uid(),sizes:p.sizes.map(s=>({...s,id:uid()})),spots:p.spots.map(s=>({...structuredClone(s),id:uid()}))})),delivery:'',deliveryNotes:'',checked:false,step:mode==='product'?2:mode==='embroidery'?3:4,updatedAt:new Date().toISOString()};}
export function resizeSpot(s:Spot,axis:'width'|'height',value:string):Spot{const next={...s,[axis]:value};if(s.lock&&s.asset&&Number(value)>0){const ratio=(s.asset.preview?.width||s.asset.width)/(s.asset.preview?.height||s.asset.height);next[axis==='width'?'height':'width']=String(Math.round((axis==='width'?Number(value)/ratio:Number(value)*ratio)*10)/10)}return next;}
export function validate(q:Quote):Issue[]{const out:Issue[]=[];const add=(step:number,target:string,message:string)=>out.push({step,target,message});
 if(!q.customer.company.trim())add(1,'customer-company','会社組織名を入力してください');
 if(!q.customer.name.trim())add(1,'customer-name','ご担当者様名を入力してください');
 if(!q.customer.phone.trim())add(1,'customer-phone','電話番号を入力してください');
 if(!q.products.length)add(3,'add-product','刺繍情報を1点以上追加してください');
 q.products.forEach((p,i)=>{const label=p.name||`刺繍対象${i+1}`;
 if(!p.spots.length)add(3,`${p.id}-spots`,`${label}：刺繍箇所を追加してください`);
 p.spots.forEach((s,j)=>{const title=`${label}・箇所${j+1}`;if(s.lettering?.enabled){if(!s.lettering.items.length)add(3,`${s.id}-lettering`,`${title}：追加する会社名または個人名を選択してください`);for(const t of s.lettering.items){if(!allowedLetteringFonts(t.personal?personalText(t.personal):t.text).includes(canonicalFont(t.font)))add(3,`${s.id}-lettering-${t.role}`,`${title}：${t.role}の文字に共通して使える書体を選択してください`);if(t.size<=10)add(3,`${s.id}-lettering-${t.role}`,`${title}：${t.role}の文字サイズは11mm以上を選択してください`);if(t.personal){if(!t.personal.noName&&t.personal.rows.some(r=>!rowName(r)))add(3,`${s.id}-lettering-${t.role}`,`${title}：個人名の苗字または名前を各行に入力してください`);if(t.personal.place==='異なる場所'&&t.personal.location==='その他'&&!t.personal.other.trim())add(3,`${s.id}-lettering-${t.role}`,`${title}：個人名の刺繍位置を入力してください`)}else if(!t.text.trim())add(3,`${s.id}-lettering-${t.role}`,`${title}：${t.role}の刺繍文字を入力してください`)}}if(!s.asset)add(3,`${s.id}-file`,`${title}：ロゴ原稿を選択してください`);if(s.location==='その他'&&!s.other.trim())add(3,`${s.id}-other`,`${title}：加工部位を入力してください`);for(const key of ['width','height'] as const)if(!Number.isFinite(Number(s[key]))||Number(s[key])<=0)add(3,`${s.id}-${key}`,`${title}：希望${key==='width'?'横幅':'高さ'}をmmで入力してください`);if(s.threadMode==='未選択')add(3,`${s.id}-thread-mode`,`${title}：糸色の選び方を選択してください`);if(s.threadMode==='指定する'&&!s.thread.trim())add(3,`${s.id}-thread`,`${title}：色見本から糸色を選んでください`);s.threadSelections?.forEach((r,k)=>{if(r.colorName!==undefined&&!r.colorName.trim())add(3,`${s.id}-color-name-${k}`,`${title}：色名を入力してください`);if(!r.number)add(3,`${s.id}-color-number-${k}`,`${title}：色見本から糸を選んでください`)});
 });
 });if(q.delivery&&!validDate(q.delivery))add(4,'delivery','受け取り希望日を確認してください');if(!q.checked)add(5,'checked','確認事項にチェックしてください');return out;
}
// Strict shape validation at the API boundary; drafts may contain empty fields.
export function parseQuote(input:unknown):Quote{
 const fail=()=>{throw new Error('保存データの形式を確認してください')};const obj=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:fail();
 const str=(v:unknown,max=5000):string=>typeof v==='string'&&v.length<=max?v:fail();const id=(v:unknown)=>{const s=str(v,64);return /^[a-zA-Z0-9-]{1,64}$/.test(s)?s:fail()};const list=(v:unknown,max:number):unknown[]=>Array.isArray(v)&&v.length<=max?v:fail();const bool=(v:unknown)=>typeof v==='boolean'?v:fail();
 const enumStr=(v:unknown,values:string[])=>typeof v==='string'&&values.includes(v)?v:fail();const raw=obj(input),c=obj(raw.customer);
 if(raw.version!==1||raw.process!=='logo-embroidery')fail();
 const q:Quote={version:1,id:id(raw.id),customerId:id(raw.customerId),process:'logo-embroidery',sourceId:raw.sourceId===null?null:id(raw.sourceId),customer:{name:str(c.name,300),company:str(c.company,300),...(c.email!==undefined?{email:str(c.email,300)}:{}),phone:str(c.phone,100),...(c.lineRegistration!==undefined?{lineRegistration:enumStr(c.lineRegistration,['未選択','登録済み','登録する','登録しない'])}:{})},delivery:str(raw.delivery,10),deliveryNotes:str(raw.deliveryNotes),checked:bool(raw.checked),step:Number(raw.step),updatedAt:str(raw.updatedAt,40),products:list(raw.products,50).map(v=>{const p=obj(v);return {id:id(p.id),name:str(p.name,300),kind:str(p.kind,100),sku:str(p.sku,100),manageNo:str(p.manageNo,100),color:str(p.color,300),...(p.colorNotes!==undefined?{colorNotes:str(p.colorNotes,500)}:{}),...(p.previewColor!==undefined?{previewColor:/^#[0-9a-fA-F]{6}$/.test(str(p.previewColor,7))?str(p.previewColor,7):fail()}:{}),material:str(p.material,500),sizes:list(p.sizes,50).map(v=>{const s=obj(v);return {id:id(s.id),size:str(s.size,50),quantity:str(s.quantity,12)}}),spots:list(p.spots,20).map(v=>{const s=obj(v);let asset:Asset|null=null;if(s.asset!==null){const a=obj(s.asset);asset={id:id(a.id),name:str(a.name,300),type:enumStr(a.type,['image/png','image/jpeg','image/webp']),width:Number(a.width),height:Number(a.height)};if(!Number.isFinite(asset.width)||!Number.isFinite(asset.height)||asset.width<=0||asset.height<=0)fail();if(a.preview!==undefined){const v=obj(a.preview);asset.preview={id:id(v.id),width:Number(v.width),height:Number(v.height)};if(!Number.isInteger(asset.preview.width)||!Number.isInteger(asset.preview.height)||asset.preview.width<1||asset.preview.height<1||asset.preview.width>1600||asset.preview.height>1600)fail()}}return {...(s.lettering!==undefined?{lettering:parseLettering(s.lettering)}:{}),id:id(s.id),location:enumStr(s.location,[...locations,'左胸','右胸','背中','左袖','右袖','正面']),other:str(s.other,300),width:str(s.width,20),height:str(s.height,20),lock:bool(s.lock),...(s.axis!==undefined?{axis:enumStr(s.axis,['width','height']) as 'width'|'height'}:{}),...(s.threadSelections!==undefined?{threadSelections:list(s.threadSelections,24).map(v=>{const t=obj(v);return {source:/^#[0-9a-fA-F]{6}$/.test(str(t.source,7))?str(t.source,7):fail(),number:enumStr(t.number,['',...threadColors.map(c=>c.number)]),...(t.colorName!==undefined?{colorName:str(t.colorName,500)}:{}),...(t.confirmed!==undefined?{confirmed:bool(t.confirmed)}:{})}})}:{}),threadMode:enumStr(s.threadMode,['未選択','業者に相談','指定する']),thread:str(s.thread,20000),pattern:enumStr(s.pattern,['あり','なし','不明']),reference:str(s.reference,500),notes:str(s.notes),asset}})}})};
 if(!Number.isInteger(q.step)||q.step<1||q.step>5||!Number.isFinite(Date.parse(q.updatedAt))||(q.delivery&&!validDate(q.delivery)))fail();
 const ids=[...q.products.flatMap(p=>[p.id,...p.sizes.map(s=>s.id),...p.spots.map(s=>s.id)])];if(new Set(ids).size!==ids.length)fail();return q;
}

export function displayAsset(a:Asset):Asset{return a.preview?{id:a.preview.id,name:a.name,type:'image/png',width:a.preview.width,height:a.preview.height}:a}

export function threadSummary(s:Spot){const mode=s.threadMode==="指定する"?"自分で糸を選ぶ":s.threadMode==="未選択"?"未選択":"刺繍屋さんに近い糸色を選択してもらう";return mode+"\n"+(s.thread||"糸番号は刺繍屋さんが確認")}

export function manualThreads(q:Quote):Quote{const next=structuredClone(q);for(const p of next.products)for(const s of p.spots){for(const t of s.lettering?.items||[]){if(t.role==='個人名'&&!t.personal){t.personal=newPersonalNames(t.text);t.personal.rows[0].id=s.id.slice(0,50)+'-personal';t.personal.previewId=t.personal.rows[0].id}}if(s.threadSelections!==undefined){s.threadSelections=s.threadSelections.filter(r=>r.colorName!==undefined||r.confirmed!==false).map(r=>({...r,colorName:r.colorName??threadColors.find(c=>c.number===r.number)?.name??''}));s.thread=manualThreadText(s.threadSelections)}}return next}
