import {db,owner,writeAccess,json,failure,boundedBody} from '@/lib/server';
import {vendorThreads,parseQuote,validate} from '@/lib/quote';
export async function GET(req:Request){try{const who=owner(req),url=new URL(req.url),id=url.searchParams.get('id');if(id){const r=await db().prepare('SELECT data, revision, status FROM embroidery_quotes WHERE id = ? AND owner = ?').bind(id,who).first<{data:string;revision:number;status:string}>();return r?json({...r,data:JSON.parse(r.data)}):json({error:'依頼が見つかりません'},404)}const status=url.searchParams.get('status')==='draft'?'draft':'saved',search=(url.searchParams.get('search')||'').slice(0,200);const result=await db().prepare('SELECT id, data, revision, updated_at FROM embroidery_quotes WHERE owner = ? AND status = ? AND instr(search, ?) > 0 ORDER BY updated_at DESC LIMIT 100').bind(who,status,search.toLowerCase()).all<{id:string;data:string;revision:number;updated_at:string}>();return json(result.results.map(r=>({...r,data:JSON.parse(r.data)})))}catch(e){return failure(e)}}
export async function POST(req:Request){try{const who=writeAccess(req);let body;try{body=JSON.parse(new TextDecoder().decode(await boundedBody(req,1_000_000)))}catch(e){if(e instanceof Response)throw e;return json({error:'保存データを確認してください'},400)}let q;try{q=vendorThreads(parseQuote(body.data))}catch{return json({error:'保存データの形式を確認してください'},400)}const status=body.status;if(!['draft','saved'].includes(status)||!Number.isInteger(body.revision)||body.revision<0)return json({error:'保存条件を確認してください'},400);if(status==='saved'&&validate(q).length)return json({error:'未入力の項目を確認してください',issues:validate(q)},400);
 const assetIds=[...new Set(q.products.flatMap(p=>p.spots.flatMap(s=>s.asset?[s.asset.id,...(s.asset.preview?[s.asset.preview.id]:[])]:[])))];for(const id of assetIds){if(!await db().prepare('SELECT id FROM embroidery_files WHERE id = ? AND owner = ?').bind(id,who).first())return json({error:'ロゴ原稿の保存を確認してください'},400)}
 const now=new Date().toISOString();q.updatedAt=now;const search=JSON.stringify([q.customer,q.id,...q.products.map(p=>[p.name,p.sku,p.manageNo])]).toLowerCase();
 const r=await db().prepare('INSERT INTO embroidery_quotes (id,owner,status,customer_id,search,data,revision,updated_at) SELECT ?,?,?,?,?,?,1,? WHERE ? = 0 ON CONFLICT(id) DO UPDATE SET search=excluded.search,data=excluded.data,revision=embroidery_quotes.revision+1,updated_at=excluded.updated_at WHERE embroidery_quotes.owner=? AND embroidery_quotes.status=\'draft\' AND excluded.status=\'draft\' AND embroidery_quotes.revision=?').bind(q.id,who,status,q.customerId,search,JSON.stringify(q),now,body.revision,who,body.revision).run();
 // An existing draft uses the same optimistic concurrency check without INSERT's new-row guard.
 if(!r.meta.changes&&body.revision>0&&status==='draft'){const changed=await db().prepare('UPDATE embroidery_quotes SET search=?,data=?,revision=revision+1,updated_at=? WHERE id=? AND owner=? AND status=\'draft\' AND revision=?').bind(search,JSON.stringify(q),now,q.id,who,body.revision).run();if(!changed.meta.changes)return json({error:'別の画面で更新されています。下書きを再読み込みして確認してください。'},409)}else if(!r.meta.changes)return json({error:'保存済みの依頼は上書きできません。新しい依頼として保存してください。'},409);
 return json({id:q.id,revision:body.revision+1,updatedAt:now});
 }catch(e){return failure(e)}}
